[package]
name = "crystal_benchmarks"
version = "1.0.0"
edition = "2021"
authors = ["Sir Charles Spikes"]
description = "7D Crystal Benchmarks"

[dependencies]
criterion = "0.5"

[[bench]]
name = "core"
harness = false
